# Generated by Django 4.2.7 on 2023-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("content", models.TextField()),
                ("is_published", models.BooleanField()),
                ("published_at", models.DateTimeField()),
            ],
        ),
    ]
