# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="published_at",
            field=models.DateField(),
        ),
    ]
