# Generated by Django 4.2.7 on 2023-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_remove_sport_content_remove_sport_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="category",
            field=models.CharField(
                choices=[
                    ("Athletics", "Athletics"),
                    ("Team_sport", "Team Sport"),
                    ("Individual_sport", "Individual Sport"),
                    ("Water_sport", "Water Sport"),
                    ("Skiing_sport", "Skiing Sport"),
                ],
                default="Athletics",
                max_length=64,
            ),
        ),
    ]
