# Generated by Django 4.2.7 on 2023-11-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('News', 'News'), ('Marketing', 'Marketing'), ('Entrepreneurship', 'Entrepreneurship')], default='Technical', max_length=65),
            preserve_default=False,
        ),
    ]
