# Generated by Django 4.2.7 on 2023-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_name_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='published_location',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
