# Generated by Django 4.2.7 on 2023-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_catagory_alter_blogs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='/images/images.jpg', upload_to='images/'),
        ),
    ]
