# Generated by Django 4.2.7 on 2023-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='/images/mainlogo.png', upload_to='images/'),
        ),
    ]
