# Generated by Django 4.2.7 on 2023-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="description",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="rating",
        ),
        migrations.AddField(
            model_name="blog",
            name="paragraph",
            field=models.TextField(default="--"),
        ),
        migrations.AddField(
            model_name="blog",
            name="release_date",
            field=models.DateField(auto_now=True),
        ),
    ]
